# Generated by Django 2.2.3 on 2020-01-20 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('pincode', models.IntegerField(verbose_name='pincode')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='college_name')),
                ('code', models.CharField(max_length=100, verbose_name='college_code')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college', to='ormmappings.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='dept_name')),
                ('code', models.CharField(max_length=100, verbose_name='dept_code')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept', to='ormmappings.College')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='subj_name')),
                ('code', models.CharField(max_length=100, verbose_name='subj_code')),
                ('remarks', models.TextField(max_length=100, verbose_name='subj_overview')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='stud_name')),
                ('age', models.IntegerField(verbose_name='stud_age')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='ormmappings.Dept')),
                ('subjs', models.ManyToManyField(related_name='students', to='ormmappings.Subject')),
            ],
        ),
    ]
